version: "3.9"

services:
  server:
    container_name: server
    build:
      context: ..
      dockerfile: deployments/${DOCKER_FILE}
    ports:
      - "8080:8080"
    volumes:
      - ..:/go/src/app
    depends_on:
      - postgres
    networks:
      - default
    environment:
      - GIN_MODE=${GIN_MODE}

  postgres:
    image: postgres
    container_name: database
    restart: always
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    logging:
      driver: none

volumes:
  data:
